/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedBriefingRouteImport } from './routes/_authenticated.briefing'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated._app'
import { Route as AuthenticatedAppCriarRouteImport } from './routes/_authenticated._app.criar'
import { Route as AuthenticatedAppConteudosRouteImport } from './routes/_authenticated._app.conteudos'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated._app.configuracoes'
import { Route as AuthenticatedAppChatIdRouteImport } from './routes/_authenticated._app.chat.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBriefingRoute = AuthenticatedBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppCriarRoute = AuthenticatedAppCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConteudosRoute =
  AuthenticatedAppConteudosRouteImport.update({
    id: '/conteudos',
    path: '/conteudos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatIdRoute = AuthenticatedAppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/conteudos': typeof AuthenticatedAppConteudosRoute
  '/criar': typeof AuthenticatedAppCriarRoute
  '/chat/$id': typeof AuthenticatedAppChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/conteudos': typeof AuthenticatedAppConteudosRoute
  '/criar': typeof AuthenticatedAppCriarRoute
  '/chat/$id': typeof AuthenticatedAppChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/briefing': typeof AuthenticatedBriefingRoute
  '/_authenticated/_app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/_app/conteudos': typeof AuthenticatedAppConteudosRoute
  '/_authenticated/_app/criar': typeof AuthenticatedAppCriarRoute
  '/_authenticated/_app/chat/$id': typeof AuthenticatedAppChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/briefing'
    | '/configuracoes'
    | '/conteudos'
    | '/criar'
    | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/briefing'
    | '/configuracoes'
    | '/conteudos'
    | '/criar'
    | '/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/_app'
    | '/_authenticated/briefing'
    | '/_authenticated/_app/configuracoes'
    | '/_authenticated/_app/conteudos'
    | '/_authenticated/_app/criar'
    | '/_authenticated/_app/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/briefing': {
      id: '/_authenticated/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof AuthenticatedBriefingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/criar': {
      id: '/_authenticated/_app/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AuthenticatedAppCriarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/conteudos': {
      id: '/_authenticated/_app/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof AuthenticatedAppConteudosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/configuracoes': {
      id: '/_authenticated/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/chat/$id': {
      id: '/_authenticated/_app/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedAppChatIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppConteudosRoute: typeof AuthenticatedAppConteudosRoute
  AuthenticatedAppCriarRoute: typeof AuthenticatedAppCriarRoute
  AuthenticatedAppChatIdRoute: typeof AuthenticatedAppChatIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppConteudosRoute: AuthenticatedAppConteudosRoute,
  AuthenticatedAppCriarRoute: AuthenticatedAppCriarRoute,
  AuthenticatedAppChatIdRoute: AuthenticatedAppChatIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedBriefingRoute: typeof AuthenticatedBriefingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedBriefingRoute: AuthenticatedBriefingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
